components:
  schemas:
    Concept:
      properties:
        description:
          title: Description
          type: string
        name:
          title: Name
          type: string
      required:
      - name
      - description
      title: Concept
      type: object
    ConceptsPayload:
      properties:
        event_ideas:
          title: Event Ideas
          type: string
        event_profile:
          $ref: '#/components/schemas/EventProfile'
        user_feedback:
          anyOf:
          - type: string
          - type: 'null'
          default: ''
          title: User Feedback
      required:
      - event_ideas
      - event_profile
      title: ConceptsPayload
      type: object
    EventProfile:
      properties:
        concept:
          anyOf:
          - type: string
          - type: 'null'
          default: ''
          title: Concept
        description:
          title: Description
          type: string
        event_datetime:
          title: Event Datetime
          type: string
        max_budget:
          title: Max Budget
          type: integer
        max_guests:
          title: Max Guests
          type: integer
        min_budget:
          title: Min Budget
          type: integer
        min_guests:
          title: Min Guests
          type: integer
        must_haves:
          items:
            type: string
          title: Must Haves
          type: array
        nice_to_haves:
          items:
            type: string
          title: Nice To Haves
          type: array
        restrictions:
          title: Restrictions
          type: string
        special_needs:
          title: Special Needs
          type: string
        things_to_avoid:
          items:
            type: string
          title: Things To Avoid
          type: array
      required:
      - description
      - min_budget
      - max_budget
      - min_guests
      - max_guests
      - event_datetime
      - must_haves
      - nice_to_haves
      - things_to_avoid
      - special_needs
      - restrictions
      title: EventProfile
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Ideas:
      properties:
        explanation:
          title: Explanation
          type: string
        name:
          title: Name
          type: string
      required:
      - name
      - explanation
      title: Ideas
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    Vendor:
      properties:
        category:
          title: Category
          type: string
        description:
          title: Description
          type: string
        ideas:
          items:
            $ref: '#/components/schemas/Ideas'
          title: Ideas
          type: array
      required:
      - category
      - description
      - ideas
      title: Vendor
      type: object
    VendorPayload:
      properties:
        event_profile:
          $ref: '#/components/schemas/EventProfile'
        user_feedback:
          anyOf:
          - type: string
          - type: 'null'
          default: ''
          title: User Feedback
      required:
      - event_profile
      title: VendorPayload
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
  /concepts:
    post:
      operationId: concepts_concepts_post
      parameters:
      - in: query
        name: user_id
        required: true
        schema:
          title: User Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConceptsPayload'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Concept'
                title: Response Concepts Concepts Post
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Concepts
  /vendors:
    post:
      operationId: vendors_vendors_post
      parameters:
      - in: query
        name: user_id
        required: true
        schema:
          title: User Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorPayload'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Vendor'
                title: Response Vendors Vendors Post
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Vendors
